# Dockerfile.user_app
FROM python:3.10.1

WORKDIR /usr/src/app

COPY config.json .
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ .

CMD ["python", "api.py"]
