# Dockerfile.app
FROM python:3.10.1

WORKDIR /usr/src/app

COPY config.json .
COPY frontend/requirements.txt .
COPY frontend/static .frontend/static
COPY frontend/templates .frontend/templates
RUN pip install --no-cache-dir -r requirements.txt

COPY frontend/ .

CMD ["python", "app.py"]
