version: '3.8'

networks:
  public:
    driver: bridge
  internal:
    driver: bridge
    internal: true   

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - ./data:/data/db    
    networks:
      - internal   

  backend_service:
    container_name: backend_service
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5001:5001"   
    depends_on:
      - mongodb
    networks:
      - internal   
      - public     

  loan_service:
    container_name: loan_service
    build:
        context: .
        dockerfile: Dockerfile.services
    ports:
        - "8001:8001"
        - "8002:8002"
        - "8003:8003"
        - "8004:8004"
    depends_on:
        - backend_service
    networks:
      - public   

  flask_frontend:
    container_name: flask_frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5002:5002"  
    depends_on:
      - backend_service
      - loan_service
    networks:
      - public   
